<h1 id="errors">Error</h1>
<p><code>kayrx::web</code>使用其自身的<code>kayrx::web::error::Error</code>类型和 <code>kayrx::web::error::ResponseError</code>特征处理来自Web处理程序的错误.</p>
<p>如果处理程序在返回<code>Result</code> 中的<code>Error</code>(指Rust <code>std::error::Error</code>特征) 也实现 <code>ResultResponseError</code>特征，<code>kayrx::web</code>将把该错误作为HTTP响应及其对应的<code>kayrx::web::http::StatusCode</code>呈现。默认情况下会生成内部服务器错误：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">pub</span> <span class="hljs-class"><span class="hljs-keyword">trait</span> <span class="hljs-title">ResponseError</span></span> {
    <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">error_response</span></span>(&amp;<span class="hljs-keyword">self</span>) -&gt; HttpResponse;
    <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">status_code</span></span>(&amp;<span class="hljs-keyword">self</span>) -&gt; StatusCode;
}
</div></code></pre>
<p>将兼容<code>Result</code>的<code>Responder</code>强制转换为HTTP响应：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">impl</span>&lt;T: Responder, E: <span class="hljs-built_in">Into</span>&lt;Error&gt;&gt; Responder <span class="hljs-keyword">for</span> <span class="hljs-built_in">Result</span>&lt;T, E&gt;
</div></code></pre>
<p>上面的代码中的<code>Error</code>是<code>kayrx::web</code>的错误定义，可以将实现<code>ResponseError</code>的任何错误自动转换.。</p>
<p>kayrx-web提供了一些常见的非<code>kayrx::web</code>错误的<code>ResponseError</code>实现。例如，如果处理程序以<code>io::Error</code>响应，则该错误将转换为<code>HttpInternalServerError</code>：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">use</span> std::io;

<span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">index</span></span>(_req: HttpRequest) -&gt; io::<span class="hljs-built_in">Result</span>&lt;fs::NamedFile&gt; {
    <span class="hljs-literal">Ok</span>(fs::NamedFile::open(<span class="hljs-string">"static/index.html"</span>)?)
}
</div></code></pre>
<p>有关<a href="https://docs.rs/kayrx/0.7.5/kayrx/web/error/trait.ResponseError.html#foreign-impls"><code>ResponseError</code>的外部实现</a>完整列表.</p>
<h2 id="%e8%87%aa%e5%ae%9a%e4%b9%89%e9%94%99%e8%af%af%e5%93%8d%e5%ba%94">自定义错误响应</h2>
<p>这是一个实现<code>ResponseError</code>示例：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">use</span> kayrx::web::{error, <span class="hljs-built_in">Result</span>};
<span class="hljs-keyword">use</span> failure::Fail;

<span class="hljs-meta">#\[derive(Fail, Debug)]</span>
<span class="hljs-meta">#\[fail(display = <span class="hljs-meta-string">"my error"</span>)]</span>
<span class="hljs-class"><span class="hljs-keyword">struct</span> <span class="hljs-title">MyError</span></span> {
    name: &amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>,
}

<span class="hljs-comment">// Use default implementation for `error_response()` method</span>
<span class="hljs-keyword">impl</span> error::ResponseError <span class="hljs-keyword">for</span> MyError {}

async <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">index</span></span>() -&gt; <span class="hljs-built_in">Result</span>&lt;&amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>, MyError&gt; {
    <span class="hljs-literal">Err</span>(MyError { name: <span class="hljs-string">"test"</span> })
}
</div></code></pre>
<p><code>ResponseError</code>有一个<code>error_response()</code>的默认实现，它将呈现 500 (内部服务器错误)，这就是在上面执行<code>index</code>处理程序时将发生的情况 .</p>
<p>覆盖<code>error_response()</code>以产生更有用的结果：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">use</span> kayrx::http::ResponseBuilder;
<span class="hljs-keyword">use</span> kayrx::web::{error, http::header, http::StatusCode, HttpResponse};
<span class="hljs-keyword">use</span> failure::Fail;

<span class="hljs-meta">#\[derive(Fail, Debug)]</span>
<span class="hljs-class"><span class="hljs-keyword">enum</span> <span class="hljs-title">MyError</span></span> {
    <span class="hljs-meta">#\[fail(display = <span class="hljs-meta-string">"internal error"</span>)]</span>
    InternalError,
    <span class="hljs-meta">#\[fail(display = <span class="hljs-meta-string">"bad request"</span>)]</span>
    BadClientData,
    <span class="hljs-meta">#\[fail(display = <span class="hljs-meta-string">"timeout"</span>)]</span>
    Timeout,
}

<span class="hljs-keyword">impl</span> error::ResponseError <span class="hljs-keyword">for</span> MyError {
    <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">error_response</span></span>(&amp;<span class="hljs-keyword">self</span>) -&gt; HttpResponse {
        ResponseBuilder::new(<span class="hljs-keyword">self</span>.status_code())
            .set_header(header::CONTENT_TYPE, <span class="hljs-string">"text/html; charset=utf-8"</span>)
            .body(<span class="hljs-keyword">self</span>.to_string())
    }

    <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">status_code</span></span>(&amp;<span class="hljs-keyword">self</span>) -&gt; StatusCode {
        <span class="hljs-keyword">match</span> *<span class="hljs-keyword">self</span> {
            MyError::InternalError =&gt; StatusCode::INTERNAL_SERVER_ERROR,
            MyError::BadClientData =&gt; StatusCode::BAD_REQUEST,
            MyError::Timeout =&gt; StatusCode::GATEWAY_TIMEOUT,
        }
    }
}

async <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">index</span></span>() -&gt; <span class="hljs-built_in">Result</span>&lt;&amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>, MyError&gt; {
    <span class="hljs-literal">Err</span>(MyError::BadClientData)
}
</div></code></pre>
<h2 id="%e9%94%99%e8%af%af%e5%8a%a9%e6%89%8b">错误助手</h2>
<p><code>kayrx::web</code>提供了一组错误帮助函数，这些函数可用于从其他错误中生成特定的HTTP错误码。在这里，我们使用<code>map_err</code>将未实现<code>ResponseError</code>特征的<code>MyError</code>转换为 400（错误请求）：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">use</span> kayrx::web::{error, <span class="hljs-built_in">Result</span>};

<span class="hljs-meta">#\[derive(Debug)]</span>
<span class="hljs-class"><span class="hljs-keyword">struct</span> <span class="hljs-title">MyError</span></span> {
    name: &amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>,
}

async <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">index</span></span>() -&gt; <span class="hljs-built_in">Result</span>&lt;&amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>&gt; {
    <span class="hljs-keyword">let</span> result: <span class="hljs-built_in">Result</span>&lt;&amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>, MyError&gt; = <span class="hljs-literal">Err</span>(MyError { name: <span class="hljs-string">"test error"</span> });

    <span class="hljs-literal">Ok</span>(result.map_err(|e| error::ErrorBadRequest(e.name))?)
}
</div></code></pre>
<p>有关 可用的错误帮助程序的完整列表，请参见<code>error</code>模块的<a href="https://docs.rs/kayrx/0.7.5/kayrx/web/error/struct.Error.html">API文档</a>.</p>
<h2 id="%e9%94%99%e8%af%af%e6%97%a5%e5%bf%97">错误日志</h2>
<p><code>kayrx::web</code>在<code>WARN</code>日志级别记录所有错误。如果将应用程序的日志级别设置为<code>DEBUG</code>并启用<code>RUST_BACKTRACE</code>，则还将记录回溯。这些可以使用环境变量进行配置：</p>
<pre><code class="language-rust"><div>&gt;&gt; RUST_BACKTRACE=<span class="hljs-number">1</span> RUST_LOG=kayrx::web=debug cargo run
</div></code></pre>
<p>该<code>Error</code>类型使用原因的错误回溯(如果可用). 如果故障根本不提供回溯，则构造一个新的回溯，指向发生转换的点(而不是错误的根源).</p>
<p>考虑将应用程序产生的错误分为两大类可能是有用的：一类是面向用户的，二类不是面向用户的.</p>
<p>这是使用的<code>middleware::Logger</code>基本示例：</p>
<pre><code class="language-rust"><div><span class="hljs-keyword">use</span> kayrx::web::{error, <span class="hljs-built_in">Result</span>};
<span class="hljs-keyword">use</span> failure::Fail;
<span class="hljs-keyword">use</span> log::debug;

<span class="hljs-meta">#\[derive(Fail, Debug)]</span>
<span class="hljs-meta">#\[fail(display = <span class="hljs-meta-string">"my error"</span>)]</span>
<span class="hljs-keyword">pub</span> <span class="hljs-class"><span class="hljs-keyword">struct</span> <span class="hljs-title">MyError</span></span> {
    name: &amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>,
}

<span class="hljs-comment">// Use default implementation for `error_response()` method</span>
<span class="hljs-keyword">impl</span> error::ResponseError <span class="hljs-keyword">for</span> MyError {}

async <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">index</span></span>() -&gt; <span class="hljs-built_in">Result</span>&lt;&amp;<span class="hljs-symbol">'static</span> <span class="hljs-built_in">str</span>, MyError&gt; {
    <span class="hljs-keyword">let</span> err = MyError { name: <span class="hljs-string">"test error"</span> };
    debug!(<span class="hljs-string">"{}"</span>, err);
    <span class="hljs-literal">Err</span>(err)
}

<span class="hljs-meta">#\[kayrx::main]</span>
async <span class="hljs-function"><span class="hljs-keyword">fn</span> <span class="hljs-title">main</span></span>() -&gt; std::io::<span class="hljs-built_in">Result</span>&lt;()&gt; {
    <span class="hljs-keyword">use</span> kayrx::web::{middleware::Logger, web, App, HttpServer};

    std::env::set_var(<span class="hljs-string">"RUST_LOG"</span>, <span class="hljs-string">"my_errors=debug,kayrx::web=info"</span>);
    std::env::set_var(<span class="hljs-string">"RUST_BACKTRACE"</span>, <span class="hljs-string">"1"</span>);
    env_logger::init();

    HttpServer::new(|| {
        App::new()
            .wrap(Logger::<span class="hljs-keyword">default</span>())
            .route(<span class="hljs-string">"/"</span>, web::get().to(index))
    })
    .bind(<span class="hljs-string">"127.0.0.1:8088"</span>)?
    .run()
    .await
}
</div></code></pre>

[set title Kayrx / error]
[set doc-section advance-error]
[stash doc-content][require raw ../_side.html]